version: "3.9"

services:
  backend:
    container_name: backend-container
    image: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 4000:3000
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: frontend-container
    image: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - frontend

  postgres:
    container_name: postgres-db
    image: postgres
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres_data:
